### ISSUE TITLE
Error: Cannot read property 'index' of null

### ISSUE THREAD

**Issue by alienlebarge** [igorshubovych/markdownlint-cli#83]
### Description

I have just installed markdownlint-cli and run into some errors.

When I run `$ markdownlint src/**/*.md`, I get the following error: 

```
Cannot read property 'index' of null
```

### Ask

Could you please help me to make it work ?

### Ho to reproduce

- Install markdown-cli `$ npm i markdownlint-cli --save-dev`
- Create a config file [`.markdownlintrc`](https://github.com/alienlebarge/alienlebargech-v3/blob/lint-markdown/.markdownlintrc)
- Run `$ npx markdownlint src/**/*.md` 

I have the same problem without the config file

### Additional Info

- markdown-cli version: 0.22.0
- [The branch where I try to install markdownlint on my blog](https://github.com/alienlebarge/alienlebargech-v3/tree/lint-markdown)

**Comment by alienlebarge** [comment]
It seems that `$ npx markdownlint README.md` work

**Comment by DavidAnson** [comment]
This sounds like a bug in one of the markdownlint rules. The stack trace you get should say which one. Can you confirm you are running the tool on these files: https://github.com/alienlebarge/alienlebargech-v3/tree/lint-markdown? If so, I should be able to clone, reproduce the problem, and investigate soon. If you want to try to narrow down which directory/file in that repository is causing the issue, that would also be helpful.

**Comment by DavidAnson** [comment]
(FYI, if you are using npx to run the tool, I think it is not necessary to also install it via npm.)

**Comment by alienlebarge** [comment]
Seems to be md039
```
$ npm run lint:markdown

> alienlebarge.ch@3.0.0 lint:markdown /Users/cedricaellen/Projects/alienlebargech-v3
> markdownlint src/**/*.md

/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdownlint/lib/markdownlint.js:762
      throw error;
      ^

TypeError: Cannot read property 'index' of null
    at /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdownlint/lib/md039.js:32:34
    at Array.forEach (<anonymous>)
    at /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdownlint/lib/md039.js:20:16
    at forToken (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdownlint/helpers/helpers.js:208:7)
    at Array.forEach (<anonymous>)
    at filterTokens (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdownlint/helpers/helpers.js:206:17)
    at Object.MD039 [as function] (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdownlint/lib/md039.js:14:5)
    at forRule (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdownlint/lib/markdownlint.js:556:20)
    at Array.forEach (<anonymous>)
    at lintContent (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdownlint/lib/markdownlint.js:602:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alienlebarge.ch@3.0.0 lint:markdown: `markdownlint src/**/*.md`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alienlebarge.ch@3.0.0 lint:markdown script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cedricaellen/.npm/_logs/2020-04-02T06_48_14_294Z-debug.log
```

**Comment by alienlebarge** [comment]
This is the following line in [this files](https://github.com/alienlebarge/alienlebargech-v3/blob/10f0dd3bd51c9d67b4f82cb74f88b01c58ef3e26/src/_content/articles/2014-08-26-jekyll-prebrowsing.md) that is causing the problem:
```
Please, read excellent [Santiago Valdarrama's article on A List Apart ](https://alistapart.com/article/one-step-ahead-improving-performance-with-prebrowsing "One Step Ahead: Improving Performance with Prebrowsing") before.
```

If I remove the space at the end of the link, there's no error anymore. https://github.com/alienlebarge/alienlebargech-v3/commit/f5ab0dabbd87c9a36029872383b14820d530e5cc

```
Please, read excellent [Santiago Valdarrama's article on A List Apart](https://alistapart.com/article/one-step-ahead-improving-performance-with-prebrowsing "One Step Ahead: Improving Performance with Prebrowsing") before.
```

**Comment by DavidAnson** [comment]
Fantastic, thank you so much for the help! I will look into this problem this evening and hope to have it fixed quickly. I was already planning a new release of the library and that will include this fix. For now, you probably want to make the change you identify above anyway and once you do, it seems like the tool runs without issues? I will assume you are not blocked and try to get this problem taken care of. Sorry for the trouble and thank you for bringing this to my attention!

**Comment by DavidAnson** [comment]
Good news, this crash was already fixed in the `next` branch by https://github.com/DavidAnson/markdownlint/commit/67d1476ed82cfd0b0db915d1e8996bbd4dff2ab5 and will be included in the next release.

**Comment by DavidAnson** [comment]
Relevant build referenced by https://github.com/igorshubovych/markdownlint-cli/commit/6e4fa47d2978403ec4eb2c8f995b7b2dcec4e84e for the next release of the CLI.

**Comment by rfay** [comment]
I've upgraded markdownlint and markdownlint-cli, still have markdownlint v0.22.0, still have this problem. What should i be doing differently?

**Comment by DavidAnson** [comment]
I haven’t published a release with the fix yet. Should happen within a week!
